2024-02-23 16:57:01,000 - INFO - 
Config:
'add_train': False
'batch_size': 64
'continue_flag': ''
'cur_time': '2024_02_23_16_57_00'
'debug_mode': False
'debug_num': 500
'do_continue_train': False
'do_figure_save': False
'do_log_print_to_screen': True
'do_log_save_to_file': True
'do_predict': True
'do_train': True
'do_train_visualized': False
'dropout_rate': 0.2
'epoch': 20
'feature_columns': [2, 3, 4, 5, 6, 7, 8]
'figure_save_path': './figure/'
'hidden_size': 128
'input_size': 7
'label_columns': [4, 5]
'label_in_feature_index': [2, 3]
'learning_rate': 0.001
'log_save_path': './log/2024_02_23_16_57_00_pytorch/'
'lstm_layers': 2
'model_name': 'model_pytorch.pth'
'model_postfix': {'pytorch': '.pth'
'keras': '.h5'
'tensorflow': '.ckpt'}
'model_save_path': './checkpoint/pytorch/'
'output_size': 2
'patience': 5
'predict_day': 3
'random_seed': 42
'shuffle_train_data': True
'time_step': 20
'train_data_path': './data/stock_data.csv'
'train_data_rate': 0.95
'use_cuda': False
'used_frame': 'pytorch'
'valid_data_rate': 0.15
2024-02-23 16:57:01,001 - ERROR - Run Error
Traceback (most recent call last):
  File "/Users/robinpeng/Desktop/gitroot/raisin/predict_ltsm/stock_predict_with_LSTM/main.py", line 241, in main
    data_gainer = Data(config)
  File "/Users/robinpeng/Desktop/gitroot/raisin/predict_ltsm/stock_predict_with_LSTM/main.py", line 105, in __init__
    self.data, self.data_column_name = self.read_data()
  File "/Users/robinpeng/Desktop/gitroot/raisin/predict_ltsm/stock_predict_with_LSTM/main.py", line 121, in read_data
    init_data = pd.read_csv(self.config.train_data_path, usecols=self.config.feature_columns)
  File "/Users/robinpeng/Desktop/gitroot/raisin/venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1024, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/robinpeng/Desktop/gitroot/raisin/venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 618, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/robinpeng/Desktop/gitroot/raisin/venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1618, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/robinpeng/Desktop/gitroot/raisin/venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1878, in _make_engine
    self.handles = get_handle(
  File "/Users/robinpeng/Desktop/gitroot/raisin/venv/lib/python3.9/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: './data/stock_data.csv'
